fitcoffee/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django import views
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # home
    path('', views.home, name='home'),
    # about
    path('about/', views.about, name='about'),
    # cafes
    path('cafes/', views.cafes_index, name='index'),
    path('cafes/<int:cafe_id>/', views.cafes_detail, name='detail'),
    path('cafes/<int:pk>/update/', views.CafeUpdate.as_view(), name='cafes_update'),
    path('cafes/<int:pk>/delete/', views.CafeDelete.as_view(), name='cafes_delete'),
    path('cafes/<int:cafe_id>/add_review/', views.add_review, name='add_review'),
    path('cafes/<int:cafe_id>/add_brewing_method/', views.add_brewing_method, name='add_brewing_method'),
    path('cafes/<int:cafe_id>/add_event/', views.add_event, name='add_event'),
    path('cafes/<int:pk>/event_update/', views.EventUpdate.as_view(), name='event_update'),
    path('cafes/map', views.FoliumView.as_view(), name='map'),
    # coffee beans
    path('coffee_beans/', views.coffee_beans_index, name='coffee_beans_index'),
    path('coffee_beans/<int:coffee_beans_id>/', views.coffee_beans_detail, name='coffee_beans_detail'),
    # auth
    path('signup/', views.signup, name="signup"),
    path('signup/register_cafe/', views.register_cafe, name="register_cafe"),
    path('signup/add_cafe', views.cafe_create, name="cafe_create"),
    path('accounts/password/reset',   auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),name='password_reset'),
    path('accounts/password/reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name= 'password_reset_done'),
    path('accounts/password/reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name = 'password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
    # user
    path('user/update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    # profile
    path('profile/', views.profile, name='profile'),
    path('profile/cafe/<int:cafe_id>/brewing_methods/update', views.brewing_method_edit, name='brewing_method_edit'),
    path('profile/cafe/<int:cafe_id>/events/', views.event_edit, name='event_edit'),
    path('profile/cafe/<int:cafe_id>/coffee_beans/', views.coffee_bean_edit, name='coffee_bean_edit'),
    path('profile/cafe/<int:cafe_id>/coffee_beans/add_coffee_bean/', views.add_coffee_bean, name='add_coffee_bean'),
    path('profile/cafe/<int:pk>/coffee_beans/update/', views.CoffeeBeanUpdate.as_view(), name='coffee_bean_update'),
    path('profile/cafe/<int:pk>/coffee_beans/delete/', views.CoffeeBeanDelete.as_view(), name='coffee_bean_delete'),
    path('profile/cafe/<int:pk>/brewing_methods/delete/', views.BrewingMethodDelete.as_view(), name='brewing_method_delete'),
    # search
    path('search/', views.search, name="search"),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

STARS = (
    ('5', '★★★★★'),
    ('4', '★★★★'),
    ('3', '★★★'),
    ('2', '★★'),
    ('1', '★'),
)

VARIETIES = (
    ('A', 'Arabica'),
    ('R', 'Robusta'),
    ('L', 'Liberica'),
    ('E', 'Excelsa')
)

BREWINGMETHOD = (
    ('DB', 'Drip Brewed'),
    ('P', 'Percolator'),
    ('FP', 'French Press'),
    ('C', 'Chezve'),
    ('P', 'Pour-over'),
    ('S', 'Syphon'),
    ('CM', 'Coffee Maker'),
    ('V', 'V60'),
    ('AP', 'Aeropress')
)

TYPE = (
    ('KID', 'Children'),
    ('MUM', 'Parent and Children'),
    ('HEA', 'Health and Wellbeing'),
    ('FIT', 'Fitness'),
    ('FOO', 'Cooking and Food'),
    ('ENT', 'Entertainment'),
    ('ART', 'Arts and Crafts')
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    is_cafe_owner = models.BooleanField(default=False, null=True)

    def __str__(self):
        return f"is {self.user.username} a cafe owner? {self.user.profile.is_cafe_owner}"
class CoffeeBean(models.Model):
    name = models.CharField(max_length=250)
    variety = models.CharField(max_length=1000, choices=VARIETIES, default=VARIETIES[0][0])
    description = models.CharField(max_length=2000)
    roastery = models.CharField(max_length=250)
    date_harvested = models.CharField(max_length=250)
    image = models.ImageField(upload_to='main_app/static/uploads', default="no image uploaded")
    location = models.CharField(max_length=250)

    def get_absolute_url(self):
        return reverse('coffee_bean_edit', kwargs={'cafe_id': self.id})

    def __str__(self):
        return self.variety

    def __str__(self):
        return self.roastery

class Cafe(models.Model):
    cafe_name = models.CharField(max_length=250)
    cafe_bio = models.CharField(max_length=2500)
    date_founded = models.DateField(null=True)
    address_line_1 = models.CharField(max_length=250)
    address_line_2 = models.CharField(max_length=250, null=True)
    address_city = models.CharField(max_length=250)
    address_county = models.CharField(max_length=250)
    address_country = models.CharField(max_length=250)
    address_postcode = models.CharField(max_length=10)
    cafe_image = models.ImageField(upload_to='main_app/static/uploads', default="no image uploaded")
    menu_image = models.ImageField(upload_to='main_app/static/uploads', default="no image uploaded")
    cafe_website = models.CharField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    coffee_beans = models.ManyToManyField(CoffeeBean, blank=True)
    longitude = models.DecimalField(decimal_places=25, max_digits=250, null=True)
    latitude = models.DecimalField(decimal_places=25, max_digits=250, null=True)
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'cafe_id': self.id})

    def __str__(self):
        return self.address_city
class Event(models.Model):
    cafe = models.ForeignKey(Cafe, on_delete=models.CASCADE)
    event_name = models.CharField(max_length=250)
    event_description = models.CharField(max_length=1000)
    event_type = models.CharField(max_length=4, choices=TYPE, default=TYPE[0][0])
    event_date = models.DateField()
    event_time_from = models.TimeField()
    event_time_to = models.TimeField()
    event_image = models.ImageField(upload_to='main_app/static/uploads', default="no image uploaded")

    def get_absolute_url(self):
        return reverse('event_edit', kwargs={'cafe_id': self.id})

    def __str__(self):
        return f"{self.get_event_type_display}"


class Review(models.Model):
    datetime = models.DateField(auto_now_add=True, null=True)
    stars = models.CharField(max_length=2, choices=STARS, default=STARS[0][0])
    review_title = models.CharField(max_length=250)
    review_body = models.CharField(max_length=1000)
    cafe = models.ForeignKey(Cafe, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

# class CafeOpening(models.Model):
#     weekday_open = models.CharField(max_length=250)
#     open_from = models.TimeField()
#     open_from = models.TimeField()
class BrewingMethod(models.Model):
    method_name = models.CharField(max_length=2, choices=BREWINGMETHOD, default=BREWINGMETHOD[0][0])
    method_image = models.ImageField(upload_to='main_app/static/uploads', default="no image uploaded")
    method_bio = models.CharField(max_length=300)
    cafe = models.ForeignKey(Cafe, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('brewing_method_edit', kwargs={'cafe_id': self.id})

    def __str__(self):
        return f"{self.get_method_name_display} on {self.method_bio}"

main_app/forms.py
from django import forms
from django.forms import ModelForm, EmailField
from .models import BrewingMethod, CoffeeBean, Profile, Event, Review, Cafe
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
class BrewingMethodForm(ModelForm):
    class Meta:
        model = BrewingMethod
        fields = ['method_name', 'method_bio']       
class CoffeeBeanForm(ModelForm):
    class Meta:
        model = CoffeeBean
        fields = ['name', 'variety', 'description', 'roastery', 'date_harvested', 'image', 'location']        
class IsCafeOwnerForm(forms.ModelForm):  
    is_cafe_owner = forms.BooleanField(required=False,label="Please check if you are signing up as a cafe owner today", widget=forms.CheckboxInput())
    class Meta:
        model = Profile
        fields = ['is_cafe_owner']
class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
  
    
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 != password2:
            raise ValidationError("Password must match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

class CafeForm(forms.ModelForm):   
    cafe_name = forms.CharField(required=False)
    cafe_bio = forms.CharField(required=False)
    date_founded = forms.DateField(required=False)
    address_line_1 = forms.CharField(required=False)
    address_line_2 = forms.CharField(required=False)
    address_city = forms.CharField(required=False)
    address_county = forms.CharField(required=False)
    address_country = forms.CharField(required=False)
    address_postcode = forms.CharField(required=False)
    cafe_image = forms.ImageField(required=False)
    menu_image = forms.ImageField(required=False)
    cafe_website = forms.CharField(required=False)

    class Meta:
        model = Cafe
        fields = ['cafe_name', 'cafe_bio', 'date_founded', 'address_line_1', 'address_line_2', 'address_city', 'address_county', 'address_country', 'address_postcode', 'cafe_image', 'menu_image', 'cafe_website']

class UserUpdateForm(UserCreationForm):
    email = EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_password(self):
        return super().clean_password2()
class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['event_name', 'event_description', 'event_type', 'event_date', 'event_time_from', 'event_time_to']

class ReviewForm(ModelForm):    
    class Meta:
        model = Review
        fields = ['review_title', 'review_body', 'stars']
        
        
        

main_app/templates/cafes/detail.html
{% extends 'base.html' %} 
{% load static %} 
{%load crispy_forms_tags %} 
{% block content %}
  <div class="container">
      <div class="container-cafe container-resp">
          <div class="card-content">
            <div class="title">{{ cafe.cafe_name }}</div>
            <div>
              <img
                src="/media/{{cafe.cafe_image}}"
                alt="My image"
                height="100"
              />
            </div>
            <div class="card-text">
              <p>{{ cafe.cafe_bio }}</p>
              <br />
              <small>
                {{ cafe.address_line_1 }}, {{ cafe.address_city }}, {{cafe.address_postcode }}
                </small>
            </div>
          </div>
          <div class="card-action">
            <a href="{{cafe.cafe_website }}">Website</a>
          </div>


        <div>
          <img
            src="/media/{{cafe.menu_image}}"
            alt="My image"
            width="320"
          />
        </div>
      </div>

      <hr />

      <div class="container-cafe  container-resp">
        <div>
          <div class="sub-title">Coffee Beans Served</div>
          {% if cafe.coffee_beans.count %} {% for coffee_bean in cafe.coffee_beans.all %}
          <div class="cafe-coffeebean-card">
            <div>
              <img
                src="/media/{{coffee_bean.image}}"
                alt="My image"
                width="100"
                class="cafe-coffee-bean-image"
              />
              <span> {{ coffee_bean.name }} - {{ coffee_bean.roastery}}</span>
            </div>
          </div>
          {% endfor %} 
          {% else %}
          <br />
          <p><em>No coffee beans listed.</em></p>
          {% endif %}
        </div>

        <div>
          <div class="sub-title">Brewing Methods</div>
          <div>
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col"></th>
                  <th scope="col">Method</th>
                  <th scope="col">Description</th>
                </tr>
              </thead>
              <tbody>
                {% for brewing_method in cafe.brewingmethod_set.all %}
                <tr>
                  <td>
                    <img
                      src="{% static 'uploads/'%}{{brewing_method.get_method_name_display}}.png"
                      alt="My image"
                      width="20"
                    />
                  </td>
                  <td>{{ brewing_method.get_method_name_display }}</td>
                  <td>{{ brewing_method.method_bio }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <hr />

      <div class="container">
        <div class="sub-title">Events</div>
        <div>
          {% if cafe.event_set.count %}
          <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">Event</th>
                <th scope="col">Description</th>
                <th scope="col">Date & Time</th>
              </tr>
            </thead>

            <tbody>
              {% for event in cafe.event_set.all %}
              <tr>
                <td>
                  <img
                    src="{% static 'uploads/'%}{{event.event_image}}"
                    alt="My image"
                    height="40"
                  />
                </td>
                <td>{{ event.event_name }}</td>
                <td>{{ event.description }}</td>
                <td>
                  {{ event.event_date }}: {{ event.event_time_from }} - {{
                  event.event_time_to}}
                </td>
              </tr>
              {% endfor %} {% else %}
            </tbody>
          </table>
          <br />
          <p><em>No Events listed.</em></p>
          {% endif %}
        </div>
      </div>

      <hr />
      <div class="container-cafe container-resp">
        <div class="review">
          <div class="sub-title">Leave a Review</div>
          <form
            class="review-form"
            method="post"
            action="{% url 'add_review' cafe.id %}"
          >
            {% csrf_token %} {{ review_form |crispy}}
            <br />
            <input type="submit" value="Add Review" class="btn" />
          </form>
        </div>

        <div>
          <div class="sub-title">Reviews</div>
          {% if cafe.review_set.count %}
          <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Date</th>
                <th scope="col">Stars</th>
                <th scope="col">Title</th>
                <th scope="col">Review</th>
              </tr>
            </thead>
            <tbody>
              {% for review in cafe.review_set.all %}
              <tr>
                <td>{{ review.datetime }}</td>
                <td>{{ review.get_stars_display }}</td>
                <td>{{ review.review_title }}</td>
                <td>{{ review.review_body }}</td>
                <td>Remove</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <br />
          {% else %}
          <p><em>No Reviews.</em></p>
          {% endif %}
        </div>
      </div>
</div>

  {% endblock %} {% block scripts %}
  <script>
    let starsEl = document.getElementById("id_stars");
    M.FormSelect.init(starsEl);
  </script>
  {% endblock scripts %}

main_app/templates/cafes/index.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %} 
{% block content %}
<div class="container">
  <div class="title">Cafes</div>
  <br />
  <!-- SEARCH BOX -->
  <div class="search-div">
    <form method="POST" action="{% url 'search' %}" class="d-flex">
      {% csrf_token %}
      <input
        type="search"
        placeholder="Search for a cafe"
        class="search text-field"
        aria-label="Search"
        name="searched"
      />
      <button type="submit" class="btn btn-search">Search</button>
    </form>
  </div>
  <br />
  <div class="filter">
    <form class="filter-form" method="get" action="">
      {{cafe_filter.form |crispy}}
      <br />
      <button class="btn" type="submit">Filter</button>
    </form>
  </div>
</div>
<div class="container-fluid">
  <div class="grid">
    {% for cafe in cafes %}
    <div class="card">
<<<<<<< HEAD
      <div class="card-img-top-container">
        <img
          class="card-img-top"
          src="/media/{{cafe.cafe_image}}"
=======
      {% load static %}
      <div class="card-img-top-container">
        <img
          class="card-img-top"
          src="{% static 'uploads/'%}{{cafe.cafe_image}}"
>>>>>>> d077c66ab554ef85f0a1e4b331ea33f96496d15e
          alt="Card image cap"
        />
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ cafe.cafe_name }}</h5>
        <p class="card-text">{{ cafe.address_city }}</p>
        <p></p>
      </div>

      <a href="/cafes/{{ cafe.id }}" class="btn explore">details</a>
    </div>
    {% endfor %}
  </div>
</div>

<script>
  let nameEl = document.getElementById("id_cafe_name");
  M.FormSelect.init(nameEl);

  let cityEl = document.getElementById("id_address_city");
  M.FormSelect.init(cityEl);
</script>

{% endblock %}

main_app/templates/cafes/map.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>fitCoffee</title>
  {{map.header.render|safe}}
  <link rel="icon" href="/../static/uploads/coffee-beans.png">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script
  src="https://code.jquery.com/jquery-3.6.1.min.js"
  integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
  crossorigin="anonymous"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
</head>
<body>
  <div class="title">Cafe Map</div>
  <h5>Click on a pin to find out more info about a cafe</h5>
  <a class="back-to-home btn" href="{% url 'index' %}" role="button">Back to Main Site!</a>
  {{map.html.render|safe}}
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  <footer class="footer mt-auto-py-3">
    <div class="container">
      <div class="row mt-5 pt-4 ">
  
        <div class="row">
          <p class="copyright mb-0">All Rights Reserved, &copy; 2022 fitCoffee &nbsp;</p>
        </div>
        
        <div class="row">
          <ul class="ftco-footer-social p-0 footer-ul">
            <li class="social">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="lightgray" class="bi bi-twitter" viewBox="0 0 16 16">
            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
              <a xlink:href="https://twitter.com/i/flow/login">
                <rect x="0" y="0" width="100%" height="100%" fill-opacity="0"/>
              </a>
            </svg>
          </li>
            <li class="social">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="lightgray" class="bi bi-instagram" viewBox="0 0 16 16">
          <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
            <a xlink:href="https://www.instagram.com/?hl=en">
              <rect x="0" y="0" width="100%" height="100%" fill-opacity="0"/>
            </a>
          </svg>
        </li>
          <li class="social">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="lightgray" class="bi bi-facebook" viewBox="0 0 16 16">
          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
            <a xlink:href="https://en-gb.facebook.com/login.php">
              <rect x="0" y="0" width="100%" height="100%" fill-opacity="0"/>
            </a>
          </svg>
        </li>
        </ul>
    </div>
  </div>
  </footer>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 
    <script>
      {{map.script.render|safe}}
    </script>
    
  </body>
  </html>

main_app/templates/cafes/search.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<div class="container">
  <div class="title">Cafes matching search term: {{searched}}</div>
  <br />
  <div class="main-cc">
    <div class="container-cc">
      <div class="row">
        {% for cafe in cafes %}

        <div class="col s4">
          <div class="border">
            <div class="card" style="width: 18rem">
              {% load static %}
              <h5 class="card-title">{{ cafe.cafe_name }}</h5>
              <img
                class="card-img-top"
                src="{% static 'uploads/'%}{{cafe.cafe_image}}"
                alt="Card image cap"
              />
              <div class="card-body">
                <p class="card-text">{{ cafe.address_city }}</p>
                <p>
                  <a href="/cafes/{{ cafe.id }}" class="btn explore">explore</a>
                </p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}